{
//=========Macro generated from canvas: c/c
//=========  (Thu Dec  1 17:17:48 2016) by ROOT version5.34/36
   TCanvas *c = new TCanvas("c", "c",2,51,600,600);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLeftMargin(0.17);
   c->SetRightMargin(0.05);
   c->SetFrameBorderMode(0);
   
   TH1F *histDeltaT = new TH1F("histDeltaT","",50,-4.4,-3.4);
   histDeltaT->SetBinContent(0,10);
   histDeltaT->SetBinContent(2,1);
   histDeltaT->SetBinContent(5,1);
   histDeltaT->SetBinContent(6,3);
   histDeltaT->SetBinContent(7,5);
   histDeltaT->SetBinContent(8,30);
   histDeltaT->SetBinContent(9,75);
   histDeltaT->SetBinContent(10,188);
   histDeltaT->SetBinContent(11,318);
   histDeltaT->SetBinContent(12,639);
   histDeltaT->SetBinContent(13,991);
   histDeltaT->SetBinContent(14,1492);
   histDeltaT->SetBinContent(15,2178);
   histDeltaT->SetBinContent(16,2948);
   histDeltaT->SetBinContent(17,3798);
   histDeltaT->SetBinContent(18,3823);
   histDeltaT->SetBinContent(19,2853);
   histDeltaT->SetBinContent(20,1563);
   histDeltaT->SetBinContent(21,798);
   histDeltaT->SetBinContent(22,289);
   histDeltaT->SetBinContent(23,127);
   histDeltaT->SetBinContent(24,63);
   histDeltaT->SetBinContent(25,33);
   histDeltaT->SetBinContent(26,17);
   histDeltaT->SetBinContent(27,12);
   histDeltaT->SetBinContent(28,18);
   histDeltaT->SetBinContent(29,9);
   histDeltaT->SetBinContent(30,5);
   histDeltaT->SetBinContent(31,5);
   histDeltaT->SetBinContent(32,3);
   histDeltaT->SetBinContent(33,4);
   histDeltaT->SetBinContent(34,5);
   histDeltaT->SetBinContent(35,3);
   histDeltaT->SetBinContent(36,1);
   histDeltaT->SetBinContent(37,5);
   histDeltaT->SetBinContent(38,1);
   histDeltaT->SetBinContent(40,1);
   histDeltaT->SetBinContent(41,1);
   histDeltaT->SetBinContent(42,1);
   histDeltaT->SetBinContent(43,2);
   histDeltaT->SetBinContent(44,1);
   histDeltaT->SetBinContent(45,2);
   histDeltaT->SetBinContent(51,12);
   histDeltaT->SetMaximum(4587.6);
   histDeltaT->SetEntries(22334);
   histDeltaT->SetStats(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-4.15,-3.95);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(2);
   gaus->SetLineWidth(2);
   gaus->SetChisquare(226.8952);
   gaus->SetNDF(8);
   gaus->GetXaxis()->SetLabelFont(42);
   gaus->GetXaxis()->SetLabelSize(0.035);
   gaus->GetXaxis()->SetTitleSize(0.035);
   gaus->GetXaxis()->SetTitleFont(42);
   gaus->GetYaxis()->SetLabelFont(42);
   gaus->GetYaxis()->SetLabelSize(0.035);
   gaus->GetYaxis()->SetTitleSize(0.035);
   gaus->GetYaxis()->SetTitleFont(42);
   gaus->SetParameter(0,3727.748);
   gaus->SetParError(0,33.6904);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,-4.067952);
   gaus->SetParError(1,0.0003636251);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,0.04515989);
   gaus->SetParError(2,0.0003031124);
   gaus->SetParLimits(2,0,0.4247653);
   histDeltaT->GetListOfFunctions()->Add(gaus);
   histDeltaT->SetLineWidth(2);
   histDeltaT->GetXaxis()->SetTitle("#Delta t [ns]");
   histDeltaT->GetXaxis()->SetRange(6,31);
   histDeltaT->GetXaxis()->SetLabelFont(42);
   histDeltaT->GetXaxis()->SetLabelSize(0.045);
   histDeltaT->GetXaxis()->SetTitleSize(0.045);
   histDeltaT->GetXaxis()->SetTitleFont(42);
   histDeltaT->GetYaxis()->SetTitle("Number of Events / 20 ps");
   histDeltaT->GetYaxis()->SetLabelFont(42);
   histDeltaT->GetYaxis()->SetLabelOffset(0.015);
   histDeltaT->GetYaxis()->SetLabelSize(0.045);
   histDeltaT->GetYaxis()->SetTitleSize(0.05);
   histDeltaT->GetYaxis()->SetTitleOffset(1.7);
   histDeltaT->GetYaxis()->SetTitleFont(42);
   histDeltaT->GetZaxis()->SetLabelFont(42);
   histDeltaT->GetZaxis()->SetLabelSize(0.035);
   histDeltaT->GetZaxis()->SetTitleSize(0.035);
   histDeltaT->GetZaxis()->SetTitleFont(42);
   histDeltaT->Draw("");
   TLatex *   tex = new TLatex(0.6,0.8,"#sigma = 45 ps");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.08,0.93,"100 GeV Electrons, 6 X_{0} Tungsten Absorber");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TPaveText *pt = new TPaveText(0.4323077,0.94,0.5676923,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("gaus");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
